Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Style/MixinUsage:
  Exclude:
    - bin/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "db/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"
    - "spec/**/*"

AllCops:
  DisplayCopNames: true
  Exclude:
    - "db/schema.rb"
